[phases.setup]
nixPkgs = ["chromium", "nodejs-18_x"]

[phases.build]
cmds = ["npm install", "npm run build"]

[phases.start]
cmd = "npm start"

[variables]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"